### ISSUE TITLE
Deploy Nublado (notebooks) Service

### ISSUE THREAD

**Issue by markgbeckett** [lsst-uk/lsp-uk#4]
... or, if Nublado proves problematic, integrate instance of Lasair notebook service.

Start by reviewing Gareth F's deployment of Jupiter Hub for Lasair.

**Comment by stvoutsin** [comment]
First version of Firefly deployed.
Demo can be found here:
http://192.41.108.30/nublado/

Notes on settng it up are here:
https://github.com/lsst-uk/lsp-uk/blob/master/notes/20200416-LSP-Openstack-Edinburgh.txt

And a a Helm chart for deploying are here:
https://github.com/lsst-uk/lsp-uk/tree/master/helm/charts/nublado

**Comment by gpfrancis** [comment]
The deployment documentation all looks good. I can now connect to Nublado OK and it appears to be working.

Some points for the next iteration:

- As previously noted, setting up HTTPS on the proxy should be an easy fix.
- There are some things (e.g. Git GUI extension) that we added for Lasair that might be useful here also, but that's probably part of a wider discussion about notebook strategy.
- I notice there's a separate stretch goal about using Heat/Terraform to automate deployment. Agree that automation is a good idea, but may want to keep other technology options open if we will be using Magnum to deploy K8s (since there will be much less work to do at the OpenStack level and relatively more configuration which might be better done with, say, Ansible).
